### ISSUE TITLE
Single User Issues within Exercise for "hands-free" tempdb in SQL Server 2022

### ISSUE THREAD

**Issue by cbattlegear** [microsoft/sqlworkshops-sql2022workshop#10]
Needed to add /m"SQLCMD" to startsqlminimal.cmd for the net start to prevent single user getting taken
Need to restart SQL in full mode after modifications before running other scripts

**Comment by rgward** [comment]
The scripts shouldn't require /m. I just use /f to start in minimal mode.

**Comment by cbattlegear** [comment]
With minimal mode I was still running into issues with my single user connection getting used by a different application/connection. Doing /f with /m and limiting it to SQLCMD worked around the issue for me. I can attempt to repro again if needed.

**Comment by rgward** [comment]
Please test again. /f doesn't put SQL Server in single user mode.

**Comment by rgward** [comment]
I went through the entire exercise today and didn't need /m. Please reopen if you find otherwise with your errors and I'll investigate it

**Comment by cbattlegear** [comment]
Attaching a screenshot below of /f showing the single user error on SQL 2022 RC0, also ran sqlservr.exe /f to verify (learned the iaas agent is probably what's taking the login on the Azure VM) which also is shown below.

![image](https://user-images.githubusercontent.com/916234/193665162-95913818-7cc6-49d1-871e-5120926b37dd.png)

![image](https://user-images.githubusercontent.com/916234/193666140-ec9dee8f-cf40-4db1-b1d3-b621f06334f5.png)

**Comment by rgward** [comment]
Gotcha. You are absolutely correct that it does start in single user as stated in our docs "Starting SQL Server in minimal configuration mode places SQL Server in single-user mode." Reopened this and will see how to fix it

**Comment by rgward** [comment]
Can you retest? I believe this should be fixed. Thanks for your patience and testing for this

**Comment by cbattlegear** [comment]
Was able to test and get past the initial issue, thanks for the patch!

**Comment by rgward** [comment]
Thank you
