### ISSUE TITLE
backupdbtos3.sql needs a minor fixup (05_DataVirt/minio/backupdbtos3.sql)

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/sqlworkshops-sql2022workshop#11]
The first backup command will fail:

BACKUP DATABASE WideWorldImporters
TO URL = 's3:/<local IP>:9000/backups/wwi.bak'
WITH CHECKSUM, INIT, FORMAT;
GO

with this error:

Msg 3078, Level 16, State 1, Line 5
The file name "s3:/10.191.80.74:9000/backups/wwi.bak" is invalid as a backup device name for the specified device type. Reissue the BACKUP statement with a valid file name and device type.
Msg 3013, Level 16, State 1, Line 5
BACKUP DATABASE is terminating abnormally.

We need to add another / before the IP address in the URL specifier.

**Comment by rgward** [comment]
Good catch. Fixed
