### ISSUE TITLE
Exercise PSPOPT - query_store_dispatcher_plan script

### ISSUE THREAD

**Issue by andyhusker** [microsoft/sqlworkshops-sql2022workshop#12]
The instructions in the PSPOPT README near the end of the script ae as follows:

"Execute the script **query_store_dispatcher_plan.sql**. If you click on the dispatcher_plan value you will see a graphical plan operator called Multiple Plan."

In the actual script, there is no label "dispatch_plan" - the relevant XML column in the resultset has no label at all.

Also - the resultset for the query returns three columns, but all three values are the same for both plans - I suggest adding the query_variant_query_id column to the query to differentiate the two rows from one another

Thanks for a great session!

**Comment by rgward** [comment]
Great suggestion. Fixed
