### ISSUE TITLE
Issue installing Polybase Feature with 2022 RC1 Eval release

### ISSUE THREAD

**Issue by SharperThanThou** [microsoft/sqlworkshops-sql2022workshop#13]
When the SQL installation attempted to install the Polybase feature, I ran across the following error presented in the installer GUI:

"The specified local group does not exist."

Upon further investigation in the Bootstrapper Install logs (detail.txt), the group shown below is apparently a requirement.  I had to create this group locally on my workstation for the feature installation to succeed.  I am a local admin, the device is domain joined, I have SQL 2017 installed (default instance), but it does not have the polybase feature enabled.  Note that the Polybase services failed to install, but to attempt again I had to change the initial installation to remove the feature and attempt reinstallation again.  Oddly, although the initial attempts failed, the installer showed that the feature successfully installed.

[Detail.txt](https://github.com/microsoft/sqlworkshops-sql2022workshop/files/10016865/Detail.txt)

(01) 2022-11-13 18:45:52 Slp: SetValue: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL16.RC1\Polybase\Configuration, Name = DMSSvcAcct
(01) 2022-11-13 18:45:52 SQLPolyBase: --RegistrySettings: Wrote registry value DMSSvcAcct = softpro\jsharp...
(01) 2022-11-13 18:45:52 SQLPolyBase: --PolybaseSetupPrivate: Configuring Odbc driver pdwodbc17e -> sqlncli17e.dll
(01) 2022-11-13 18:45:52 SQLPolyBase: --PolybaseSetupPrivate: Creating performance counters: RC1...
(01) 2022-11-13 18:45:58 SQLPolyBase: --PolybaseSetupPrivate: Creating event sources: RC1...
(01) 2022-11-13 18:45:58 SQLPolyBase: --PolybaseSetupPrivate: Creating Access Group
(01) 2022-11-13 18:45:58 Slp: Sco: Attempting to initialize user group PdwComputeNodeAccess
(01) 2022-11-13 18:45:58 Slp: Sco: Attempting to check if user group PdwComputeNodeAccess exists
(01) 2022-11-13 18:45:58 Slp: Sco: Attempting to open root DirectoryEntry object for local computer
(01) 2022-11-13 18:45:58 Slp: Sco: Attempting to check if container 'WinNT://SPRO-L301511,computer' of group exists
(01) 2022-11-13 18:45:58 Slp: Prompting user if they want to retry this action due to the following failure:
(01) 2022-11-13 18:45:58 Slp: ----------------------------------------
(01) 2022-11-13 18:45:58 Slp: The following is an exception stack listing the exceptions in outermost to innermost order
(01) 2022-11-13 18:45:58 Slp: Inner exceptions are being indented
(01) 2022-11-13 18:45:58 Slp: 
(01) 2022-11-13 18:45:58 Slp: Exception type: Microsoft.SqlServer.Configuration.Sco.ScoException
(01) 2022-11-13 18:45:58 Slp:     Message: 
(01) 2022-11-13 18:45:58 Slp:         The specified local group does not exist.
(01) 2022-11-13 18:45:58 Slp:         
(01) 2022-11-13 18:45:58 Slp:     HResult : 0x84bb0001
(01) 2022-11-13 18:45:58 Slp:         FacilityCode : 1211 (4bb)
(01) 2022-11-13 18:45:58 Slp:         ErrorCode : 1 (0001)
(01) 2022-11-13 18:45:58 Slp:     Data: 
(01) 2022-11-13 18:45:58 Slp:       WatsonData = LOCAL
(01) 2022-11-13 18:45:58 Slp:       DisableRetry = true
(01) 2022-11-13 18:45:58 Slp:     Inner exception type: System.Runtime.InteropServices.COMException
(01) 2022-11-13 18:45:58 Slp:         Message: 
(01) 2022-11-13 18:45:58 Slp:                 The specified local group does not exist.
(01) 2022-11-13 18:45:58 Slp:                 
(01) 2022-11-13 18:45:58 Slp:         HResult : 0x80070560
(01) 2022-11-13 18:45:58 Slp:         Stack: 
(01) 2022-11-13 18:45:58 Slp:                 at System.DirectoryServices.DirectoryEntries.Find(String name, String schemaClassName)
(01) 2022-11-13 18:45:58 Slp:                 at Microsoft.SqlServer.Configuration.Sco.UserGroup.Exists()
(01) 2022-11-13 18:45:58 Slp: ----------------------------------------

**Comment by rgward** [comment]
Thanks for reporting this. I remember when you hit this in the class. Although not directly an issue with the workshop I get it is a problem because you need the feature for exercises in the workshop. I'll forward this to our team to investigate.

**Comment by HugoMSFT** [comment]
@SharperThanThou do you happen to remember if your SQL 2017 installation was upgraded from a SQL Server 2016 instance?
Thank you for bringing this up, I'll route it internally and see how we can fix it.
