### ISSUE TITLE
Rendered markdown for ctrl directions

### ISSUE THREAD

**Issue by sqlknowitall** [microsoft/sqlworkshops-sql2022workshop#2]
https://github.com/microsoft/sqlworkshops-sql2022workshop/tree/main/sql2022workshop/03_BuiltinQueryIntelligence/pspopt#see-a-workload-problem-for-psp "See a workload problem for PSP", step 5, it should be ctrl+c but it is just showing as + in the rendered markdown

**Comment by rgward** [comment]
Nice catch. Fixed
