### ISSUE TITLE
Fast Execution on MaxDOP Query

### ISSUE THREAD

**Issue by ScaryDBA** [microsoft/sqlworkshops-sql2022workshop#24]
For whatever reason, my queries were running in about 5 seconds and didn't break the 10 second threshold. I'd suggest adding a second XE session so people can quickly identify whether or not their queries are running fast.

**Comment by rgward** [comment]
Fixed by putting in comments in the readme about 10 second execution and using XEProfiler to confirm. Then can use possibly more uses with -n to get eligiblity.
