### ISSUE TITLE
Misspelled reference to file name query_store_parent_query.sql

### ISSUE THREAD

**Issue by sqlknowitall** [microsoft/sqlworkshops-sql2022workshop#3]
https://github.com/microsoft/sqlworkshops-sql2022workshop/tree/main/sql2022workshop/03_BuiltinQueryIntelligence/pspopt#solve-the-problem-in-sql-server-2022-with-no-code-changes  Solve the problem in SQL Server 2022 with no code changes, step number 7 is missing part of the file name; query_store_parent.sql  should be query_store_parent_query.sql

**Comment by rgward** [comment]
thank you for this catch. Fixed
