### ISSUE TITLE
Non-Distinct File Names in WWI Backups

### ISSUE THREAD

**Issue by dbo-Josh** [microsoft/sqlworkshops-sql2022workshop#35]
Not all of the included wwi backups have unique filenames, preventing all 3 from being restored at the same time. Adjusting the filenames to be unique would make things easier for users to set up.

**Comment by rgward** [comment]
Thanks for this feedback. We have a big workshop coming in March so I'm going to defer making changes here until after that. I do want to change it so you can do this.

**Comment by rgward** [comment]
I've decided to leave everything "as is". Each exercise includes a restore script that removes an existing database of the same name. I also included in the prereqs a statement that you will restore each backup in each exercise instead of all of them upfront.
