### ISSUE TITLE
Specify that Top Resource Consuming Queries report is in Query Store

### ISSUE THREAD

**Issue by sqlknowitall** [microsoft/sqlworkshops-sql2022workshop#4]
https://github.com/microsoft/sqlworkshops-sql2022workshop/tree/main/sql2022workshop/03_BuiltinQueryIntelligence/pspopt#solve-the-problem-in-sql-server-2022-with-no-code-changes Solve the problem in SQL Server 2022 with no code changes, step 5, references the top resource consuming queries report in ssms, but not specifically that it is in the Query Store vs Standard Reports

**Comment by rgward** [comment]
fixed
