### ISSUE TITLE
pspopt demo - need to clear plan cache before re-running demo with perfmon.

### ISSUE THREAD

**Issue by DavidMMaxwell** [microsoft/sqlworkshops-sql2022workshop#5]
current instructions from readme.md for pspopt demo: https://github.com/microsoft/sqlworkshops-sql2022workshop/blob/main/sql2022workshop/03_BuiltinQueryIntelligence/pspopt/readme.md 

...
## See a PSP problem for a single query execution

1. Set the actual execution plan option in SSMS. Run **query_plan_seek.sql** **twice** in a query window in SSMS. Note the query execution time is fast (< 1 second). Check the timings from SET STATISTICS TIME ON from the second execution. The query is run twice so the 2nd execution will not require a compile. This is the time we want to compare. Note the query plan uses an Index Seek.
2. In a different query window set the actual execution option in SSMS. Run **query_plan_scan.sql** in a query windows in SSMS. Note the query plan uses an Clustered Index Scan and parallelism.
3. Now go back and run **query_plan_seek.sql** again. Note that even though the query executes quickly (< 1 sec), the timing from SET STATISTICS TIME is significantly longer than the previous execution. Also note the query plan also uses a clustered index scan and parallelism.

## See a workload problem for PSP

1. Setup perfmon to capture % processor time and batch requests/second.
2. Run **workload_index_seek.cmd 10** from the command prompt. This should finish very quickly. The parameter is the number of users. You may want to increase this for machines with 8 CPUs or more. Observe perfmon counters.
3. Run **workload_index_scan.cmd**. This should take longer but now locks into cache a plan for a scan.
...

Between those two demos, attendees will need to clear the proc cache again so that the second demo does not start by using the parallel scan plan.

**Comment by rgward** [comment]
Very nice catch. Added a script called clear.sql and put in the readme
