### ISSUE TITLE
Landing Zone Prerequisite

### ISSUE THREAD

**Issue by PrometheusRising1** [microsoft/sqlworkshops-sql2022workshop#55]
Synapse Link exercise instructions reference a Landing Zone in the Prereqs.  However, there  do not appear to be any prerequisites for a landing zone (not in the Readme.md on the main page nor in the exercises, nor in the slides).

**Comment by rgward** [comment]
This is called out in the readme under the Setup the exercise section

Create a new Azure storage account to be used for Azure Data Lake Storage Gen2 which is the Landing Zone. You must check the Enable hierarchical namespace option. Create a container for this storage account. You now need to grant access for the Synapse workspace to the landing zone storage account.
