### ISSUE TITLE
Title in Notebook backuprestores3.ipynb is incorrect

### ISSUE THREAD

**Issue by sqlknowitall** [microsoft/sqlworkshops-sql2022workshop#6]
https://github.com/microsoft/sqlworkshops-sql2022workshop/tree/main/sql2022workshop/05_DataVirt/s3objectstorage backuprestores3.ipynb title within notebook is incorrect: references the delta query as opposed to backup restore

**Comment by rgward** [comment]
Thanks for the catch. Fixed
