### ISSUE TITLE
Add to Prereqs about Polybase constraints on install

### ISSUE THREAD

**Issue by Datachick** [microsoft/sqlworkshops-sql2022workshop#65]
Add to the prereqs that Polybase can be installed only once so that attendees know ahead of time and can make the right decision of how to set up their lab environments.

This addition may save a lot of time and pain for getting the labs done.

**Comment by rgward** [comment]
This is already called out in the prereqs on the main readme page

Exercises in Module 5 require the PolyBase Query Service for External Data Feature (using all defaults). **IMPORTANT**: If you have an instance from a previous version of SQL Server already on your computer or VM that has the Polybase feature enabled you will have to remove that feature from that instance or uninstall that instance. If this is not possible Module 5 does have T-SQL notebooks for you to view the experience
