### ISSUE TITLE
Consider adding a script for Ledger Module

### ISSUE THREAD

**Issue by Datachick** [microsoft/sqlworkshops-sql2022workshop#66]
Consider adding a script or to the script about controlling DDL changes to Ledger Tables.  This could show the sorts of "normal" table ALTERs that can be done: certain datatype changes, adding columns, removing columns, etc.

This might help alleviate the concerns by devs and DBAs that Ledger tables are set in stone.

**Comment by rgward** [comment]
thanks for the suggestion but there are a lot of exercises already in the module. What I will do is summarize a few things from this part of the doc that talks about what is allowed or not allowed for schema changes: https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-limits?source=recommendations&view=sql-server-ver16#schema-changes-consideration
