### ISSUE TITLE
Update to Prerequisites

### ISSUE THREAD

**Issue by BobPusateri** [microsoft/sqlworkshops-sql2022workshop#67]
Preqreqs doc says you can use a VM in azure, so I spun up an Azure SQL VM. But it appears that Polybase Query Service is not included in a SQL VM (I did SQL 2022 Developer on Windows Server 2022), and I didn't notice any options to include Polybase when building the VM so I assumed it was just included. Either way it definitely couldn't be enabled.

So if there is in fact no way to enable Polybase when building a SQL VM, I'd note that in the prereqs doc because right now it looks like I should be able to use that.

**Comment by rgward** [comment]
It is not installed as a feature from the marketplace images but it can be added as a feature. Added a comment in the prereqs for this.
