### ISSUE TITLE
Missing Scale for TempDB Exercise

### ISSUE THREAD

**Issue by PrometheusRising1** [microsoft/sqlworkshops-sql2022workshop#71]
(https://github.com/microsoft/sqlworkshops-sql2022workshop/tree/main/sql2022workshop/04_Engine)/tempdb/readme.md

Missing scale for SQL Server:Wait Statistics/Page latch waits/Waits started per second (per your videos on YouTube, should be 0.01)

**Comment by rgward** [comment]
fixed
