### ISSUE TITLE
backuprestores3.ipynb - EXIST WHERE clause does not match CREATE for certificate.

### ISSUE THREAD

**Issue by DavidMMaxwell** [microsoft/sqlworkshops-sql2022workshop#8]
Exist check uses IP without port in the WHERE clause, but creates the cert with the port number in the name. 

Current: 

USE MASTER
GO
IF EXISTS (SELECT * FROM sys.credentials WHERE name = 's3://<local IP>/backups')
	DROP CREDENTIAL [s3://<local IP>:9000/backups];
GO

Should be: 

USE MASTER
GO
IF EXISTS (SELECT * FROM sys.credentials WHERE name = 's3://<local IP>:9000/backups')
	DROP CREDENTIAL [s3://<local IP>:9000/backups];
GO

**Comment by DavidMMaxwell** [comment]
Huh - code between carets was removed in the comment. (let me know if it's not clear)

**Comment by rgward** [comment]
fixed in notebook
